CREATE DATABASE ManualPecas;
--CREATE DATABASE M_ManualPecas;
--CREATE DATABASE T_ManualPecas;

USE ManualPecas

CREATE TABLE Fornecedores(
	FornecedorId INT PRIMARY KEY IDENTITY NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	CNPJ CHAR(18) UNIQUE NOT NULL
);

CREATE TABLE Pecas(
	PecaId INT PRIMARY KEY IDENTITY NOT NULL,
	Codigo VARCHAR(255) UNIQUE NOT NULL,
	Descricao TEXT NOT NULL
);

CREATE TABLE FornecedoresPecas(
	FornecedorId INT FOREIGN KEY REFERENCES Fornecedores(FornecedorId),
	PecaId INT FOREIGN KEY REFERENCES Pecas(PecaId),
	Preco DECIMAL(10,2) NOT NULL
);
